# pipeline autogen by mkdkr_exporter
# https://gitlab.com/rosiney.gp/mkdkr_exporter

name: CI

on: [push]

jobs:
  lint_shellcheck:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: lint shellcheck
      run: make lint.shellcheck
  lint_flake8:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: lint flake8
      run: make lint.flake8
  lint_black:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: lint black
      run: make lint.black
  lint_commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: lint commit
      run: make lint.commit
  test_unit_3_8:
    runs-on: ubuntu-22.04
    needs:
      - lint_shellcheck
      - lint_flake8
      - lint_black
      - lint_commit
    steps:
    - uses: actions/checkout@v1
    - name: test unit_3_8
      run: make test.unit_3_8
  test_unit_3_9:
    runs-on: ubuntu-22.04
    needs:
      - lint_shellcheck
      - lint_flake8
      - lint_black
      - lint_commit
    steps:
    - uses: actions/checkout@v1
    - name: test unit_3_9
      run: make test.unit_3_9
  test_unit_3_10:
    runs-on: ubuntu-22.04
    needs:
      - lint_shellcheck
      - lint_flake8
      - lint_black
      - lint_commit
    steps:
    - uses: actions/checkout@v1
    - name: test unit_3_10
      run: make test.unit_3_10
